import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Wrapper from "@/components/wrapper";
import Providers from "@/provider/providers";

const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  style: ["normal", "italic"],
  display: "swap",
  subsets: ["latin"],
  variable: "--font-faustina",
});

export const metadata: Metadata = {
  title: "Valentina",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <Providers>
          <Wrapper>{children}</Wrapper>
        </Providers>
      </body>
    </html>
  );
}
